version: "3.2"

services:
  cat:
    image: cdunkelb/https-nginx:cat-v5
    deploy:
      replicas: 1
      labels:
        com.docker.lb.hosts: cat.example.com
        com.docker.lb.network: animal
        com.docker.lb.port: 443
        com.docker.lb.ssl_passthrough: "true"
    environment:
      METADATA: end-to-end-TLS
    networks:
      - animal
    secrets:
      - source: animal_private_key
        target: /etc/nginx/key.pem
      - source: animal_public_key
        target: /etc/nginx/cert.pem

  dog:
    image: cdunkelb/https-nginx:dog-v5
    deploy:
      replicas: 1
      labels:
        com.docker.lb.hosts: dog.example.com
        com.docker.lb.network: animal
        com.docker.lb.port: 443
        com.docker.lb.ssl_passthrough: "true"
    environment:
      METADATA: end-to-end-TLS
    networks:
      - animal
    secrets:
      - source: animal_private_key
        target: /etc/nginx/key.pem
      - source: animal_public_key
        target: /etc/nginx/cert.pem

networks:
  animal:
    driver: overlay

secrets:
  animal_private_key:
    file: animal-key.pem
  animal_public_key:
    file: animal-cert.pem
